<a href="https://colab.research.google.com/github/AyeshaMalikAyesha/DataEngineering/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

1. Numpy a numerical python is a library that is used to store numerical data n-dimensional array.
2. It is used to perform mathematical computations so it is MATLAB replacement and it is also used in Machine Learning.
3. It is faster than list as it occupies less space in memory while list will contain the space for object type,object value,Reference pointer, size.
4. It contains all the elements of same type so no type checking is required.
5. It occupies contiguous space in memory.

**Importing Libraries**

In [1]:
pip install numpy

**Importing Libraries**

In [2]:
import numpy as np

**How numpy is faster**

In [5]:
import time
size=100000
l1=range(size)
l2=range(size)

start=time.time()
[x+y for x,y in zip(l1,l2)]
print(f'Time taken by list is {time.time()-start}')


arr1=np.arange(size)
arr2=np.arange(size)

start=time.time()
arr1+arr2
print(f'Time taken by numpy is {time.time()-start}')


Time taken by list is 0.017165660858154297
Time taken by numpy is 0.0006687641143798828


(range(0, 10), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

**Creating numpy arrays**

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,20,2) # 0 is start point, 20 is end point and 2 is step size

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
scalar=np.array(5)
scalar

array(5)

In [33]:
vector=np.array([1,2,3,4])
print(vector)
print(f'Shape of array is {vector.shape}')
print(f'Size of array is {vector.size}')
print(f'Data type of array is {vector.dtype}')
print(f'Dimension of array is {vector.ndim}')
print(f'Size of every element of array is {vector.itemsize}')

[1 2 3 4]
Shape of array is (4,)
Size of array is 4
Data type of array is int64
Dimension of array is 1
Size of every element of array is 8


In [22]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1,np.reshape(arr1,(3,2))

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

Datatypes used in numpy are float8,float16,float32,float64,int8,int16 etc. The higher the precision the more exactly the numbers will be stored in memory.

In [25]:
arr2=np.array([1,2,3],dtype=np.float32)
arr2

array([1., 2., 3.], dtype=float32)

In [29]:
arr3=np.array([1,2,3,4],dtype=complex)
arr3

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

**Printing Array**

In [35]:
arr=np.array([[1,2,3],[4,5,6]])

for row in arr:
  print(row)
  for elem in row:
    print(elem)


[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [36]:
# Corder
arr=np.array([[1,2,3],[4,5,6]])
for cell in np.nditer(arr,order='C'):
  print(cell)

1
2
3
4
5
6


In [37]:
# Fotran Order
arr=np.array([[1,2,3],[4,5,6]])
for cell in np.nditer(arr,order='F'):
  print(cell)

1
4
2
5
3
6


**Flatten the array**

In [40]:
arr=np.array([[1,2,3],[4,5,6]])
arr.flatten()

array([1, 2, 3, 4, 5, 6])

**Accessing/Changing specific elements,rows,columns**

In [41]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [45]:
arr[0][-1],arr[0,-1]

(6, 6)

In [51]:
arr[:,-1]

array([ 6, 12])

In [54]:
arr[:,-2]

array([ 5, 11])

In [48]:
arr[:,1::2]

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [50]:
arr[:,1:-1:2]

array([[ 2,  4],
       [ 8, 10]])

In [55]:
# get specific row
arr[1,:]

array([ 7,  8,  9, 10, 11, 12])

In [57]:
arr[1,-1]=17
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 17]])

In [58]:
arr[0,1:3]=[22,33]
arr

array([[ 1, 22, 33,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 17]])

In [127]:
# 3 dimensional array
arr3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr3)
print(f'Data type of array is {arr3.dtype}')
print(f'Shape of array is {arr3.shape}')
print(f'Size of array is {arr3.size}')

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
Data type of array is int64
Shape of array is (2, 2, 4)
Size of array is 16


In [130]:
arr3[:,:,[0,2,3]]

array([[[ 1,  3,  4],
        [ 5,  7,  8]],

       [[ 9, 11, 12],
        [13, 15, 16]]])

In [65]:
arr3[:,:-1,-3]

array([[ 2],
       [10]])

In [66]:
arr3[:,1,2]=[17,17]
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6, 17,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 17, 16]]])

In [72]:
arr3[0,:,:2]=[[11,12],[15,16]]
arr3

array([[[11, 12,  3,  4],
        [15, 16, 17,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 17, 16]]])

**Initializing Different Types of Arrays**

In [4]:
np.zeros(shape=(3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
ones=np.ones(shape=(4,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.full((3,2),4)

array([[4, 4],
       [4, 4],
       [4, 4]])

In [8]:
np.full(ones.shape,3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [11]:
np.full_like(ones,5)

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [12]:
np.random.rand(3,2)

array([[0.67343475, 0.87809885],
       [0.92285958, 0.30028741],
       [0.45962445, 0.74532934]])

In [16]:
np.random.randint(0,10,(3,2))

array([[4, 6],
       [2, 1],
       [2, 4]])

In [18]:
a=np.array([[1,2,3],[4,5,6]])
np.random.random_sample(a.shape)

array([[0.88913202, 0.28266265, 0.07150447],
       [0.29781502, 0.36942606, 0.79673516]])

In [21]:
# Identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [28]:
# Repeat the array 3 times across 0 axis
print(np.repeat(arr,3,axis=0))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]]]


In [25]:
# Repeat the array 3 times across 1 axis
print(np.repeat(arr,3,axis=1))

[[[ 1  2  3]
  [ 1  2  3]
  [ 1  2  3]
  [ 4  5  6]
  [ 4  5  6]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 7  8  9]
  [ 7  8  9]
  [10 11 12]
  [10 11 12]
  [10 11 12]]]


In [26]:
# Repeat the array 3 times across axis 2
print(np.repeat(arr,3,axis=2))

[[[ 1  1  1  2  2  2  3  3  3]
  [ 4  4  4  5  5  5  6  6  6]]

 [[ 7  7  7  8  8  8  9  9  9]
  [10 10 10 11 11 11 12 12 12]]]


In [31]:
arr=np.array([[1,2,3],[4,5,6]])
arr,np.repeat(arr,2,axis=0),np.repeat(arr,2,axis=1)

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [1, 2, 3],
        [4, 5, 6],
        [4, 5, 6]]),
 array([[1, 1, 2, 2, 3, 3],
        [4, 4, 5, 5, 6, 6]]))

In [32]:
arr=np.array([1,2,3])
arr,np.repeat(arr,2,axis=0)

(array([1, 2, 3]), array([1, 1, 2, 2, 3, 3]))

**Copying the array**

In [36]:
a=np.array([1,2,3])
b=a
a[0]=100
b[1]=90
a,b

(array([100,  90,   3]), array([100,  90,   3]))

In [38]:
a=np.array([1,2,3])
b=np.copy(a)
a[0]=100
b[1]=90
a,b

(array([100,   2,   3]), array([ 1, 90,  3]))

**Mathematics**

In [39]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [42]:
# addition
2+a,a-2,a+a,a**2

(array([3, 4, 5]), array([-1,  0,  1]), array([2, 4, 6]), array([1, 4, 9]))

In [43]:
a=np.array([1,2,3])
b=np.array([1,2,3])
a**b

array([ 1,  4, 27])

In [45]:
np.cos(a),np.sin(a),np.tan(a)

(array([ 0.54030231, -0.41614684, -0.9899925 ]),
 array([0.84147098, 0.90929743, 0.14112001]),
 array([ 1.55740772, -2.18503986, -0.14254654]))

**Linear Algebra**

In [48]:
m1=np.array([[1,2,3],[4,5,6]])
m2=np.array([[1,2,3],[4,5,6]])
np.matmul(m1,np.reshape(m2,(3,2)))

array([[22, 28],
       [49, 64]])

**Determinant**

In [53]:
a=np.identity(4)
np.linalg.det(a)

1.0

**Statistics**

In [61]:
stats=np.array([[1,12,13],[44,5,6]])
stats

array([[ 1, 12, 13],
       [44,  5,  6]])

In [62]:
np.max(stats)

44

In [63]:
np.min(stats)

1

In [64]:
np.max(stats,axis=0),np.max(stats,axis=1)

(array([44, 12, 13]), array([13, 44]))

In [73]:
np.sum(stats),np.sum(stats,axis=0),np.sum(stats,axis=1)

(81, array([45, 17, 19]), array([26, 55]))

**Reorganizing Arrays**

In [75]:
# Reshape array
arr=np.array([[1,2,3],[4,5,6]])
np.reshape(arr,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [79]:
# Vstack,hstack
a=np.array([1,2,3])
b=np.array([4,5,6])
np.vstack([a,b]),np.hstack([a,b]),np.vstack([a,b,a])

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([1, 2, 3, 4, 5, 6]),
 array([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3]]))

In [82]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
np.vstack([a,b]),np.hstack([a,b])

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]))

In [91]:
# Splitting of array
a=np.array([[1,2,3,4],[5,6,7,8]])
np.split(a,2),np.vsplit(a,2),np.hsplit(a,2)

([array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])],
 [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])],
 [array([[1, 2],
         [5, 6]]),
  array([[3, 4],
         [7, 8]])])

**Quiz**

Given the matrix. Find the following:
1. [[4,5],[24,25],[29,30]]
2. [2,8,14,20]
3. [[11,12],[16,17]]

In [92]:
matrix=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [96]:
matrix[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [100]:
matrix[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [103]:
matrix[2:4,:2]

array([[11, 12],
       [16, 17]])

**Miscellaneous**

In [108]:
data=np.genfromtxt('data.txt',delimiter=',')
data=data.astype('int32')
data=data.reshape((2,9))
data

array([[12,  1,  3, 14,  2,  3,  4,  5,  6],
       [ 6,  7,  5,  6,  7,  4,  3,  2,  4]], dtype=int32)

In [110]:
data<10

array([[False,  True,  True, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [113]:
np.any(data<10,axis=0),np.any(data<10,axis=1)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True]),
 array([ True,  True]))

In [115]:
np.all(data<10,axis=0),np.all(data<10,axis=1)

(array([False,  True,  True, False,  True,  True,  True,  True,  True]),
 array([False,  True]))

In [119]:
arr=np.arange(100)
np.savetxt('arr.txt',arr)

In [122]:
filedata=np.loadtxt('arr.txt')
filedata=filedata.astype('int64')
filedata

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

**Boolean masking and advanced indexing**

In [123]:
filedata

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [125]:
(filedata>50) & (filedata<100)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [126]:
~((filedata>50) & (filedata<100))

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])